### ISSUE TITLE
Bugs in user profile page: 1. When we view the comments section in the user profile, the user name is displayed wrongly. It is displaying the first and last names. 2.If the user has not posted any comments or posts, there should be a message like'the user has not posted yet'

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#131]

**Comment by ksowndar** [comment]
It is fixed in following PR, please check it and also screenshots are attached
https://github.com/MilesUpHQ/reddit-clone-rails/pull/133
![image](https://user-images.githubusercontent.com/84360457/210781816-fdff08e8-5f30-47f2-a589-8c415a2c36e2.png)
![image](https://user-images.githubusercontent.com/84360457/210781886-f6d5f4a6-5048-449f-ad2c-a466ad5c32cf.png)
