### ISSUE TITLE
At the admin side, community page -  the account column should display the name of the community creator. Right now it is displaying their account id.

### ISSUE THREAD

**Issue by 78-karthi** [MilesUpHQ/reddit-clone-rails#169]

**Comment by ksowndar** [comment]
It is fixed, now the name of community owner is visible instead of account id, Please check in following PR and image is attached below, please verify it @78-karthi 
https://github.com/MilesUpHQ/reddit-clone-rails/pull/178
![image](https://user-images.githubusercontent.com/84360457/211742008-11300d02-86fe-4117-8703-cf35a0b685c1.png)
